[template]
authors = ["{{author_name}} <{{email}}>"]
description = "A template for creating a new Rust project"
keywords = ["rust", "project", "template"]
categories = ["command-line-utilities"]
exclude = ["spec/*"]

[placeholders]
author_name = { type = "string", prompt = "Your name" }
email = { type = "string", prompt = "Your email address" }
